require:
  - rubocop-rails

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.3
  Exclude:
    - 'db/schema.rb'
    - 'db/migrate/**/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'bin/**/*'
    - 'tmp/**/*'

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/MethodLength:
  Max: 30

Metrics/BlockLength:
  Enabled: false

Layout/LineLength:
  Max: 120
